import FunctionFieldLittlewood
#check FunctionFieldLittlewood.ParityDescent.geometric_parity_forced_factor
#check FunctionFieldLittlewood.RootStream.stream_root_enumeration
#check FunctionFieldLittlewood.RootStream.stream_filtered_root_enumeration
#check FunctionFieldLittlewood.certificate_sound
#check FunctionFieldLittlewood.hankel_kernel_iff
#check FunctionFieldLittlewood.checkOptimalCertificate_sound_all
#check FunctionFieldLittlewood.exactCertificate_normalise_iff
#check FunctionFieldLittlewood.optimal_polynomial_nonzero
#check FunctionFieldLittlewood.shiftedLaurent_coeff
#check FunctionFieldLittlewood.certificate_laurent_sound
#check FunctionFieldLittlewood.polynomialLittlewoodProduct_bound_iff
#check FunctionFieldLittlewood.certificate_polynomialLittlewoodProduct
#check FunctionFieldLittlewood.laiSprang17_sharp_first
#check FunctionFieldLittlewood.laiSprang3_comparison_first
#check FunctionFieldLittlewood.thueMorse_even
#check FunctionFieldLittlewood.thueMorse_odd
#print axioms FunctionFieldLittlewood.ParityDescent.geometric_parity_forced_factor
#print axioms FunctionFieldLittlewood.RootStream.stream_root_enumeration
#print axioms FunctionFieldLittlewood.RootStream.stream_filtered_root_enumeration
#print axioms FunctionFieldLittlewood.certificate_sound
#print axioms FunctionFieldLittlewood.hankel_kernel_iff
#print axioms FunctionFieldLittlewood.checkOptimalCertificate_sound_all
#print axioms FunctionFieldLittlewood.exactCertificate_normalise_iff
#print axioms FunctionFieldLittlewood.optimal_polynomial_nonzero
#print axioms FunctionFieldLittlewood.shiftedLaurent_coeff
#print axioms FunctionFieldLittlewood.certificate_laurent_sound
#print axioms FunctionFieldLittlewood.polynomialLittlewoodProduct_bound_iff
#print axioms FunctionFieldLittlewood.certificate_polynomialLittlewoodProduct
#print axioms FunctionFieldLittlewood.laiSprang17_sharp_first
#print axioms FunctionFieldLittlewood.laiSprang3_comparison_first
#print axioms FunctionFieldLittlewood.thueMorse_even
#print axioms FunctionFieldLittlewood.thueMorse_odd
