"""Reproduce selected finite Lean fixtures from retained, independently checked data.

The export is untrusted input: Lean's `decide` checks its primal/dual identities.
Stream identity beyond the recorded prefix is not formalised by this export.
Run from the repository root; --check verifies the tracked file without writing.
"""
import argparse
import json
from pathlib import Path

from search.finite_rank import PrefixResult, check_result
from search.run_rank_experiments import oracle


SOURCE = Path('results/2026-09-18-rank-search.jsonl')
TARGET = Path('FunctionFieldLittlewood/SavedCertificates.lean')
SELECTION = [
    ('thueMorse', 'thue_morse', 2, 9, 15),
    ('forcedEndpoint', 'thue_morse', 2, 1, 2),
    ('laiSprang17', 'lai_sprang', 17, 0, 17),
]


def render():
    rows = [json.loads(line) for line in SOURCE.read_text().splitlines()]
    parts = ['''-- Generated by python3 -m search.export_lean_certificates; do not edit.
import FunctionFieldLittlewood.DualCertificate

namespace FunctionFieldLittlewood.Saved

-- Recorded finite prefixes, padded by zero. Infinite-stream identity is not proved.
set_option maxRecDepth 10000
set_option maxHeartbeats 2000000
''']
    for label, name, p, d, m in SELECTION:
        matches = [row for row in rows
                   if (row['stream'], row['p'], row['d'], row['m']) == (name, p, d, m)]
        if len(matches) != 1:
            raise ValueError(f'expected exactly one input: {label}')
        row = matches[0]
        result = PrefixResult(**row['result'])
        a = lambda n: oracle(name, p, n)
        if result.j is None or not check_result(p, a, d, m, row['limit'], result):
            raise ValueError(f'expected a valid resolved certificate: {label}')
        j = result.j
        end = m+d+j
        prefix = [0] + [a(n) for n in range(1, end+1)]
        parts.append(f'''-- {name}, F_{p}, d={d}, m={m}, j={j}; {result.obstruction['kind']} dual.
def {label}Prefix (n : ℕ) : ZMod {p} :=
  ({prefix} : List (ZMod {p})).getD n 0

def {label}R (i : Fin {d+1}) : ZMod {p} :=
  ({list(result.R)} : List (ZMod {p})).getD i.val 0

def {label}Weights (k : Fin {j+1}) : ZMod {p} :=
  ({result.obstruction['weights']} : List (ZMod {p})).getD k.val 0

theorem {label}_accepted :
    checkOptimalCertificate {label}Prefix {label}R {m} {j} {label}Weights = true := by
  decide

/-- Every extension of this recorded prefix inherits the checked finite optimum. -/
theorem {label}_optimal_of_prefix (a : ℕ → ZMod {p})
    (ha : ∀ n, n ≤ {end} → {label}Prefix n = a n) :
    FirstNonzero a {label}R {m} {j} ∧
      ∀ S : Fin {d+1} → ZMod {p}, S 0 = 1 → S (Fin.last {d}) ≠ 0 →
        ∃ k : ℕ, 0 < k ∧ k ≤ {j} ∧ fractionalCoeff a S {m} k ≠ 0 := by
  apply checkOptimalCertificate_sound a {label}R {m} {j} {label}Weights
  rw [← checkOptimalCertificate_congr_prefix {label}Prefix a {label}R {m} {j}
    {label}Weights ha]
  exact {label}_accepted

#print axioms {label}_accepted
#print axioms {label}_optimal_of_prefix
''')
    parts.append('''-- A zero dual, a changed terminal index and a bad endpoint must be rejected.
example : checkOptimalCertificate forcedEndpointPrefix forcedEndpointR 2 1
    (fun _ => 0) = false := by decide
example : checkOptimalCertificate forcedEndpointPrefix forcedEndpointR 2 2
    (fun _ => 1) = false := by decide
example : checkOptimalCertificate forcedEndpointPrefix
    (fun i : Fin 2 => if i = 0 then 1 else 0) 2 1 forcedEndpointWeights = false := by decide

-- The forced-endpoint fixture has a kernel, but no admissible endpoint in it.
example : (∀ i : Fin 2, dualRow forcedEndpointPrefix 2 forcedEndpointWeights i = 0)
    = False := by decide
example : DualObstruction forcedEndpointPrefix 2 1 0 (fun _ => (0 : ZMod 2))
    = False := by decide

#print axioms dualRow_eval
#print axioms dualObstruction_sound
#print axioms checkOptimalCertificate_sound
#print axioms optimal_first_le
#print axioms checkOptimalCertificate_congr_prefix

end FunctionFieldLittlewood.Saved
''')
    return '\n'.join(parts)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if TARGET.read_text() != rendered:
            raise SystemExit('tracked Lean fixture differs from regenerated data')
        print('3 independently checked saved certificates match the Lean fixtures')
    else:
        TARGET.write_text(rendered)
        print(f'wrote {TARGET}')
