-- Generated by python3 -m search.export_lean_certificates; do not edit.
import FunctionFieldLittlewood.DualCertificate

namespace FunctionFieldLittlewood.Saved

-- Recorded finite prefixes, padded by zero. Infinite-stream identity is not proved.
set_option maxRecDepth 10000
set_option maxHeartbeats 2000000

-- thue_morse, F_2, d=9, m=15, j=24; inconsistent dual.
def thueMorsePrefix (n : ℕ) : ZMod 2 :=
  ([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0] : List (ZMod 2)).getD n 0

def thueMorseR (i : Fin 10) : ZMod 2 :=
  ([1, 1, 0, 0, 0, 0, 0, 0, 1, 1] : List (ZMod 2)).getD i.val 0

def thueMorseWeights (k : Fin 25) : ZMod 2 :=
  ([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] : List (ZMod 2)).getD k.val 0

theorem thueMorse_accepted :
    checkOptimalCertificate thueMorsePrefix thueMorseR 15 24 thueMorseWeights = true := by
  decide

/-- Every extension of this recorded prefix inherits the checked finite optimum. -/
theorem thueMorse_optimal_of_prefix (a : ℕ → ZMod 2)
    (ha : ∀ n, n ≤ 48 → thueMorsePrefix n = a n) :
    FirstNonzero a thueMorseR 15 24 ∧
      ∀ S : Fin 10 → ZMod 2, S 0 = 1 → S (Fin.last 9) ≠ 0 →
        ∃ k : ℕ, 0 < k ∧ k ≤ 24 ∧ fractionalCoeff a S 15 k ≠ 0 := by
  apply checkOptimalCertificate_sound a thueMorseR 15 24 thueMorseWeights
  rw [← checkOptimalCertificate_congr_prefix thueMorsePrefix a thueMorseR 15 24
    thueMorseWeights ha]
  exact thueMorse_accepted

#print axioms thueMorse_accepted
#print axioms thueMorse_optimal_of_prefix

-- thue_morse, F_2, d=1, m=2, j=1; leading_zero dual.
def forcedEndpointPrefix (n : ℕ) : ZMod 2 :=
  ([0, 1, 1, 0, 1] : List (ZMod 2)).getD n 0

def forcedEndpointR (i : Fin 2) : ZMod 2 :=
  ([1, 1] : List (ZMod 2)).getD i.val 0

def forcedEndpointWeights (k : Fin 2) : ZMod 2 :=
  ([0, 1] : List (ZMod 2)).getD k.val 0

theorem forcedEndpoint_accepted :
    checkOptimalCertificate forcedEndpointPrefix forcedEndpointR 2 1 forcedEndpointWeights = true := by
  decide

/-- Every extension of this recorded prefix inherits the checked finite optimum. -/
theorem forcedEndpoint_optimal_of_prefix (a : ℕ → ZMod 2)
    (ha : ∀ n, n ≤ 4 → forcedEndpointPrefix n = a n) :
    FirstNonzero a forcedEndpointR 2 1 ∧
      ∀ S : Fin 2 → ZMod 2, S 0 = 1 → S (Fin.last 1) ≠ 0 →
        ∃ k : ℕ, 0 < k ∧ k ≤ 1 ∧ fractionalCoeff a S 2 k ≠ 0 := by
  apply checkOptimalCertificate_sound a forcedEndpointR 2 1 forcedEndpointWeights
  rw [← checkOptimalCertificate_congr_prefix forcedEndpointPrefix a forcedEndpointR 2 1
    forcedEndpointWeights ha]
  exact forcedEndpoint_accepted

#print axioms forcedEndpoint_accepted
#print axioms forcedEndpoint_optimal_of_prefix

-- lai_sprang, F_17, d=0, m=17, j=15; inconsistent dual.
def laiSprang17Prefix (n : ℕ) : ZMod 17 :=
  ([0, 8, 8, 0, 8, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8] : List (ZMod 17)).getD n 0

def laiSprang17R (i : Fin 1) : ZMod 17 :=
  ([1] : List (ZMod 17)).getD i.val 0

def laiSprang17Weights (k : Fin 16) : ZMod 17 :=
  ([9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] : List (ZMod 17)).getD k.val 0

theorem laiSprang17_accepted :
    checkOptimalCertificate laiSprang17Prefix laiSprang17R 17 15 laiSprang17Weights = true := by
  decide

/-- Every extension of this recorded prefix inherits the checked finite optimum. -/
theorem laiSprang17_optimal_of_prefix (a : ℕ → ZMod 17)
    (ha : ∀ n, n ≤ 32 → laiSprang17Prefix n = a n) :
    FirstNonzero a laiSprang17R 17 15 ∧
      ∀ S : Fin 1 → ZMod 17, S 0 = 1 → S (Fin.last 0) ≠ 0 →
        ∃ k : ℕ, 0 < k ∧ k ≤ 15 ∧ fractionalCoeff a S 17 k ≠ 0 := by
  apply checkOptimalCertificate_sound a laiSprang17R 17 15 laiSprang17Weights
  rw [← checkOptimalCertificate_congr_prefix laiSprang17Prefix a laiSprang17R 17 15
    laiSprang17Weights ha]
  exact laiSprang17_accepted

#print axioms laiSprang17_accepted
#print axioms laiSprang17_optimal_of_prefix

-- A zero dual, a changed terminal index and a bad endpoint must be rejected.
example : checkOptimalCertificate forcedEndpointPrefix forcedEndpointR 2 1
    (fun _ => 0) = false := by decide
example : checkOptimalCertificate forcedEndpointPrefix forcedEndpointR 2 2
    (fun _ => 1) = false := by decide
example : checkOptimalCertificate forcedEndpointPrefix
    (fun i : Fin 2 => if i = 0 then 1 else 0) 2 1 forcedEndpointWeights = false := by decide

-- The forced-endpoint fixture has a kernel, but no admissible endpoint in it.
example : (∀ i : Fin 2, dualRow forcedEndpointPrefix 2 forcedEndpointWeights i = 0)
    = False := by decide
example : DualObstruction forcedEndpointPrefix 2 1 0 (fun _ => (0 : ZMod 2))
    = False := by decide

#print axioms dualRow_eval
#print axioms dualObstruction_sound
#print axioms checkOptimalCertificate_sound
#print axioms optimal_first_le
#print axioms checkOptimalCertificate_congr_prefix

end FunctionFieldLittlewood.Saved
